### PR TITLE
Added support for Taxonomies and Terms

### PR DESCRIPTION
**Pull request by makkinga**

### CODE REVIEW

**Comment by aryehraber** [comment]
Thanks for all the work @makkinga!

One small issue, I just had a look at the diff and it looks like all spaces have been changed to tabs... Now, I don't want to start a [tabs vs. spaces](https://www.youtube.com/watch?v=SsoOG6ZeyUI) battle, but I'd prefer to stick with the existing spaces, mostly to be able to read a more accurate diff since now it shows all files are completely rewritten.

After that, I'm happy to merge this in!

**Comment by makkinga** [comment]
@aryehraber I wouldn't mind a tabs vs spaces battle 😜 I'm in team spaces though. Not realy sure why that happened. Probably because I recently reinstalled PHPStorm. I'll have it updated asap

**Comment by aryehraber** [comment]
Yeah PSR-2 would be great! _Most_ of the code should already follow it I think... If PHPStorm finds a lot of mistakes, feel free to autocorrect them. Though it's honestly not a big deal, as long as the spacing thing is fixed, I'm happy to leave it as is for now.

**Comment by makkinga** [comment]
Tabs should be gone

**Comment by aryehraber** [comment]
Awesome, thanks!

**Comment by aryehraber** [comment]
Getting reports that fetching Collections no longer works after merging this, seeing the same on my local copy. Gonna have to revert to the prev version for now.

**Pull request merged**
