### PR TITLE
Related content was missing slug and order aot

### PR DESCRIPTION
**Pull request by makkinga**

### CODE REVIEW

**Comment by makkinga** [comment]
@aryehraber The latter. It shouldnt have any side effects. 
It still returns all the data it did before plus some extra like slug, url, order, last_modified etc.

**Comment by aryehraber** [comment]
Perfect, thanks again!

**Comment by makkinga** [comment]
For example in my test:

**data()**
```
array:8 [▼
  "title" => ""
  "preview_image" => ""
  "body" => array:4 []
  "meta_title" => ""
  "meta_description" => ""
  "id" => ""
]
```

**toArray()**
```
array:23 [▼
  "title" => ""
  "fieldset" => ""
  "preview_image" => ""
  "body" => array:4 []
  "meta_title" => ""
  "meta_description" => ""
  "id" => ""
  "slug" => ""
  "url" => ""
  "uri" => false
  "url_path" => false
  "permalink" => ""
  "edit_url" => ""
  "published" => true
  "order" => null
  "order_type" => "alphabetical"
  "collection" => ""
  "is_entry" => true
  "last_modified" => 1534861739
  "content" => null
  "content_raw" => null
]
```

**Comment by aryehraber** [comment]
I can see situations where I wouldn't want all those details shared on the frontend, and I'd only want the actual content data. Perhaps in the future this can become configurable, to give devs a little more control as to what is returned.

**Pull request merged**
