### PR TITLE
Added support for Taxonomies and Terms

### PR DESCRIPTION
**Pull request by makkinga**
Added support to fetch taxonomies and terms

### CODE REVIEW

**Comment by makkinga** [comment]
Resolving the conflicts now

**Comment by aryehraber** [comment]
Awesome @makkinga, actually had someone ask for this end of last week 😄 

Will merge when the conflicts are resolved!

**Comment by makkinga** [comment]
Nah.. starting over with a new fork

**Comment by makkinga** [comment]
@aryehraber I see the processing of the data is rerouted a bit so ill make a new fork and merge/ test it local.

Fetching nav is comming next. Already built it but wanted to make a seperate PR for it

**Comment by aryehraber** [comment]
Yeah, there were some recent changes to that -- no breaking changes for users, but for devs it's a bit different. 

Thanks for the work on this and Nav 👍

**Pull request closed without merging**
