### PR TITLE
Added support for nav

### PR DESCRIPTION
**Pull request by makkinga**

### CODE REVIEW

**Comment by makkinga** [comment]
@aryehraber Hold on for a minute.. forgot to update the docs

**Comment by makkinga** [comment]
@aryehraber Ready to be reviewed

**Comment by aryehraber** [comment]
Hey @makkinga, thanks for this!

I haven't been able to do a test run yet, but I noticed a formatting change that I'm not super keen on. I prefer follow the standard of adding a space after using the not operator (`!`), eg:
```php
if (! $this->someMethod()) {
    //
}
```

I usually let little things like this slide if it's 1-2 methods, but since (presumably) PHPStorm auto-corrected this I'd prefer restore if that's ok? I can also merge it in and fix it up myself, no problemo, but I would imagine PHPStorm is just gonna do it again next time 😅

**Comment by makkinga** [comment]
No problem.. I tought PSR-2 did that but cant find any rule for this.. I'll have it updated

**Comment by aryehraber** [comment]
Hey @makkinga, I've left this one pending as it seems to also hold your Taxonomy PR code (which broke other parts of Fetch, so I had to revert earlier this week). Or is that all fixed in this PR?

**Comment by makkinga** [comment]
Oh.. I did test it but didn't see anything that broke.. I can remove the taxonomy code from this PR and make a new one for that.. can you tell me how to reproduce the issue?

**Comment by aryehraber** [comment]
It seems any Fetch call that returns a collection/array of data throws an exception (eg: Collections and Pages).

If you download and install [v4.3](https://github.com/aryehraber/statamic-fetch/releases/tag/v4.3) and then Fetch a Collection (eg: `/!/Fetch/collection/blog`), I get the following error:

screenshot 2018-11-22 at 10 17 48

**Comment by makkinga** [comment]
It does indeed.. removed it from this PR though and that fixed it. I'll have a look into the issue and make you a new PR for the taxonomies

**Comment by makkinga** [comment]
@aryehraber found the issue.. and I did fix that before.

row 529 of `Fetch.php` should be
```
return $this->goDeep($value);
```

instead of 
```
return $this->goDeep([$key => $value]);
```

**Comment by aryehraber** [comment]
Closing for now, please see: https://github.com/aryehraber/statamic-fetch/pull/37#issuecomment-443166272

**Pull request closed without merging**
